services:
  kafka:
    image: bitnami/kafka:3.6.1
    restart: unless-stopped
    container_name: kafka-server
    hostname: kafka-server
    environment:
      # Core Broker Settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # Single Broker Optimization
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1

      # Resource Management
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms1G
      - KAFKA_CFG_LOG_RETENTION_HOURS=24

      # Threading Configuration
      - KAFKA_CFG_NUM_IO_THREADS=4
      - KAFKA_CFG_NUM_NETWORK_THREADS=2

      # Consumer Group Settings
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=3000
      - KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS=6000
      - KAFKA_CFG_GROUP_MAX_SESSION_TIMEOUT_MS=300000

      # Log Management
      - KAFKA_CFG_LOG_RETENTION_BYTES=1073741824 # 1GB
      - KAFKA_CFG_LOG_SEGMENT_BYTES=536870912 # 512MB
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_DELETE_RETENTION_MS=86400000 # 24 hours
      - KAFKA_CFG_MIN_CLEANABLE_DIRTY_RATIO=0.5

      # Performance Tuning
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_CFG_MAX_CONNECTIONS_PER_IP=50

      # Topic Management
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami/kafka"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "9000:8080"

volumes:
  kafka_data:
