version: "3.8"

name: kafka

services:
  kafka:
    extends:
      file: docker-compose-kafka.yml
      service: kafka
  
  kafka-ui:
    extends:
      file: docker-compose-kafka.yml
      service: kafka-ui

volumes:
  kafka_data:
